Reply by category
sumuh/Trollbot pull request #18
Opened 2021-06-01 11:02 UTC by WitCanStain

Some code cleanup.

2021-06-01 11:22 UTC, vornsami approved these changes

2021-06-02 07:26 UTC, macwille commented
Omalla koneella ohjelma hajoaa kun painaa Clear-nappia. Controllerin käyttämä axios.delete ei taida palauta automaattisesti kuin HTTP statuksen, kuitenkin nyt se taitaa odottaa data tägissä JSON-oliota.

2021-06-02 07:33 UTC, macwille requested changes
Voisi vielä varmistaa että Clear-toiminto toimii oikein. Omalla koneella ei toiminut.

2021-06-02 08:45 UTC, kafenoir commented
Ei toiminut Clear munkaan koneella.

2021-06-06 11:51 UTC, merged